x-api-common: &api-common
  build: .
  network_mode: host
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "150M"
  environment: &api-env
    INDEX_PATH: "/app/resources/index.bin"
    LISTEN_TCP: "1"
    PORT: "9999"
    HOST: "0.0.0.0"
    TCP_NODELAY: "1"
    SO_REUSEPORT_ENABLED: "1"
    IVF_NPROBE: "8"
    IVF_FULL_NPROBE: "24"
    CANDIDATES: "0"

services:
  api1:
    <<: *api-common
    container_name: rinha-c-api1

  api2:
    <<: *api-common
    container_name: rinha-c-api2
